# Generated by Django 6.0.1 on 2026-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=20)),
                ('gst_percent', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
