# Generated by Django 6.0.1 on 2026-01-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('sale_date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('transporter_name', models.CharField(max_length=100)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_weight', models.IntegerField()),
                ('bag_count', models.IntegerField()),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
        ),
    ]
