# Generated by Django 6.0.1 on 2026-01-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_mill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='related_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.purchase'),
        ),
    ]
