# Generated by Django 6.0.1 on 2026-01-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
