# Generated by Django 6.0.1 on 2026-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sale_broker_name_alter_sale_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transport_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_paid_by_customer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_paid_by_dealer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
