# Generated by Django 6.0.1 on 2026-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_broker_remove_sale_broker_name_sale_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_rate_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
