# Generated by Django 6.0.1 on 2026-01-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sale_total_ton_sale_transport_rate_per_ton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_ton',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transport_rate_per_ton',
        ),
    ]
