# Generated by Django 6.0.1 on 2026-01-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_sale_total_ton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='amount',
            new_name='sell_amount',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='rate_per_kg',
            new_name='sell_rate_per_kg',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='buy_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='source_purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.purchaseitem'),
        ),
    ]
