# Generated by Django 6.0.1 on 2026-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_amount_saleitem_sell_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='source_purchase_item',
            new_name='purchase_item',
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_rate_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sell_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
