# Generated by Django 6.0.1 on 2026-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_source_purchase_item_saleitem_purchase_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='buy_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='buy_rate_per_kg',
            new_name='rate_per_kg',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='purchase_item',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sell_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sell_rate_per_kg',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
